# Site settings
title: Sébastien Vaucher
description: Personal website of Sébastien Vaucher, engineer in software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://seb.vaucher.org" # the base hostname & protocol for your site
twitter_username: sebyx31
github_username:  sebyx31
timezone: Europe/Zurich

collections:
  projects:
    output: false

defaults:
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
      image: "empty.png"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed
